-- Seed the exercise library from the exercise database spreadsheet.
-- Run after schema.sql. 252 exercises.
-- NOTE: `short` and `target_weight` are left at defaults (null / 0) since
-- the source sheet doesn't have them. Fill in target_weight and setup_fields
-- per exercise as you introduce it in an onboarding/setup flow, or leave at
-- 0 and let the cold-start logic in targetFor() handle it.

insert into exercises (name, equipment, equipment_type, primary_muscle, secondary_muscles, muscle_group, mechanism, pattern) values
  ('Barbell Flat Bench Press', ARRAY['Barbell','Bench']::text[], 'Barbell', 'Pectoralis Major', ARRAY['Anterior Deltoid','Triceps']::text[], 'Chest', 'Push', 'press'),
  ('Dumbbell Flat Bench Press', ARRAY['Dumbbells','Bench']::text[], 'Dumbbell', 'Pectoralis Major', ARRAY['Anterior Deltoid','Triceps']::text[], 'Chest', 'Push', 'press'),
  ('Machine Flat Chest Press', ARRAY['Machine']::text[], 'Machine', 'Pectoralis Major', ARRAY['Anterior Deltoid','Triceps']::text[], 'Chest', 'Push', 'press'),
  ('Smith Machine Flat Press', ARRAY['Smith Machine','Bench']::text[], 'Machine', 'Pectoralis Major', ARRAY['Anterior Deltoid','Triceps']::text[], 'Chest', 'Push', 'press'),
  ('Barbell Incline Bench Press', ARRAY['Barbell','Incline Bench']::text[], 'Barbell', 'Upper Pectoralis Major', ARRAY['Anterior Deltoid','Triceps']::text[], 'Chest', 'Push', 'press'),
  ('Dumbbell Incline Bench Press', ARRAY['Dumbbells','Incline Bench']::text[], 'Dumbbell', 'Upper Pectoralis Major', ARRAY['Anterior Deltoid','Triceps']::text[], 'Chest', 'Push', 'press'),
  ('Machine Incline Chest Press', ARRAY['Machine']::text[], 'Machine', 'Upper Pectoralis Major', ARRAY['Anterior Deltoid','Triceps']::text[], 'Chest', 'Push', 'press'),
  ('Smith Machine Incline Press', ARRAY['Smith Machine','Bench']::text[], 'Machine', 'Upper Pectoralis Major', ARRAY['Anterior Deltoid','Triceps']::text[], 'Chest', 'Push', 'press'),
  ('Barbell Decline Bench Press', ARRAY['Barbell','Decline Bench']::text[], 'Barbell', 'Lower Pectoralis Major', ARRAY['Anterior Deltoid','Triceps']::text[], 'Chest', 'Push', 'press'),
  ('Dumbbell Decline Bench Press', ARRAY['Dumbbells','Decline Bench']::text[], 'Dumbbell', 'Lower Pectoralis Major', ARRAY['Anterior Deltoid','Triceps']::text[], 'Chest', 'Push', 'press'),
  ('Machine Decline Chest Press', ARRAY['Machine']::text[], 'Machine', 'Lower Pectoralis Major', ARRAY['Anterior Deltoid','Triceps']::text[], 'Chest', 'Push', 'press'),
  ('Barbell Floor Press', ARRAY['Barbell']::text[], 'Barbell', 'Pectoralis Major', ARRAY['Triceps','Anterior Deltoid']::text[], 'Chest', 'Push', 'press'),
  ('Dumbbell Floor Press', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Pectoralis Major', ARRAY['Triceps','Anterior Deltoid']::text[], 'Chest', 'Push', 'press'),
  ('Flat Dumbbell Fly', ARRAY['Dumbbells','Bench']::text[], 'Dumbbell', 'Pectoralis Major', ARRAY['Anterior Deltoid']::text[], 'Chest', 'Push', 'fly'),
  ('Incline Dumbbell Fly', ARRAY['Dumbbells','Incline Bench']::text[], 'Dumbbell', 'Upper Pectoralis Major', ARRAY['Anterior Deltoid']::text[], 'Chest', 'Push', 'fly'),
  ('Decline Dumbbell Fly', ARRAY['Dumbbells','Decline Bench']::text[], 'Dumbbell', 'Lower Pectoralis Major', ARRAY['Anterior Deltoid']::text[], 'Chest', 'Push', 'fly'),
  ('High-to-Low Cable Fly', ARRAY['Cable Machine']::text[], 'Cable', 'Lower Pectoralis Major', ARRAY['Anterior Deltoid']::text[], 'Chest', 'Push', 'fly'),
  ('Mid-Level Cable Fly', ARRAY['Cable Machine']::text[], 'Cable', 'Pectoralis Major', ARRAY['Anterior Deltoid']::text[], 'Chest', 'Push', 'fly'),
  ('Low-to-High Cable Fly', ARRAY['Cable Machine']::text[], 'Cable', 'Upper Pectoralis Major', ARRAY['Anterior Deltoid']::text[], 'Chest', 'Push', 'fly'),
  ('Machine Pec Deck Fly', ARRAY['Machine']::text[], 'Machine', 'Pectoralis Major', ARRAY['Anterior Deltoid']::text[], 'Chest', 'Push', 'fly'),
  ('Bodyweight Push-Up', ARRAY['None']::text[], 'Bodyweight', 'Pectoralis Major', ARRAY['Triceps','Anterior Deltoid','Core']::text[], 'Chest', 'Push', 'press'),
  ('Deficit Push-Up', ARRAY['Plates / Blocks']::text[], 'Other', 'Pectoralis Major', ARRAY['Triceps','Anterior Deltoid','Core']::text[], 'Chest', 'Push', 'press'),
  ('Weighted Push-Up', ARRAY['Weight Plate / Vest']::text[], 'Other', 'Pectoralis Major', ARRAY['Triceps','Anterior Deltoid','Core']::text[], 'Chest', 'Push', 'press'),
  ('Incline Push-Up', ARRAY['Bench / Box']::text[], 'Other', 'Lower Pectoralis Major', ARRAY['Triceps','Anterior Deltoid']::text[], 'Chest', 'Push', 'press'),
  ('Decline Push-Up', ARRAY['Bench / Box']::text[], 'Other', 'Upper Pectoralis Major', ARRAY['Triceps','Anterior Deltoid']::text[], 'Chest', 'Push', 'press'),
  ('Diamond Push-Up', ARRAY['None']::text[], 'Bodyweight', 'Triceps, Pectoralis Major', ARRAY['Anterior Deltoid','Core']::text[], 'Chest', 'Push', 'press'),
  ('Bodyweight Chest Dip', ARRAY['Dip Station']::text[], 'Bodyweight', 'Lower Pectoralis Major', ARRAY['Triceps','Anterior Deltoid']::text[], 'Chest', 'Push', 'press'),
  ('Weighted Chest Dip', ARRAY['Dip Station','Belt']::text[], 'Bodyweight', 'Lower Pectoralis Major', ARRAY['Triceps','Anterior Deltoid']::text[], 'Chest', 'Push', 'press'),
  ('Machine Assisted Dip', ARRAY['Assisted Dip Machine']::text[], 'Other', 'Lower Pectoralis Major', ARRAY['Triceps','Anterior Deltoid']::text[], 'Chest', 'Push', 'press'),
  ('Dumbbell Squeeze Press', ARRAY['Dumbbells','Bench']::text[], 'Dumbbell', 'Pectoralis Major', ARRAY['Triceps','Anterior Deltoid']::text[], 'Chest', 'Push', 'press'),
  ('Plate Svend Press', ARRAY['Weight Plate']::text[], 'Other', 'Pectoralis Major', ARRAY['Anterior Deltoid']::text[], 'Chest', 'Push', 'press'),
  ('Landmine Chest Press', ARRAY['Barbell','Landmine']::text[], 'Barbell', 'Pectoralis Major', ARRAY['Anterior Deltoid','Triceps']::text[], 'Chest', 'Push', 'press'),
  ('Dumbbell Pullover', ARRAY['Dumbbell','Bench']::text[], 'Dumbbell', 'Pectoralis Major, Lats', ARRAY['Triceps','Serratus Anterior']::text[], 'Chest', 'Push/Pull', 'pullover'),
  ('Standing Barbell Overhead Press', ARRAY['Barbell']::text[], 'Barbell', 'Anterior Deltoid', ARRAY['Lateral Deltoid','Triceps','Core']::text[], 'Shoulders', 'Push', 'press'),
  ('Seated Barbell Overhead Press', ARRAY['Barbell','Bench']::text[], 'Barbell', 'Anterior Deltoid', ARRAY['Lateral Deltoid','Triceps']::text[], 'Shoulders', 'Push', 'press'),
  ('Standing Dumbbell Press', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Anterior Deltoid', ARRAY['Lateral Deltoid','Triceps','Core']::text[], 'Shoulders', 'Push', 'press'),
  ('Seated Dumbbell Press', ARRAY['Dumbbells','Bench']::text[], 'Dumbbell', 'Anterior Deltoid', ARRAY['Lateral Deltoid','Triceps']::text[], 'Shoulders', 'Push', 'press'),
  ('Arnold Press', ARRAY['Dumbbells','Bench']::text[], 'Dumbbell', 'Anterior & Lateral Deltoid', ARRAY['Triceps','Upper Traps']::text[], 'Shoulders', 'Push', 'press'),
  ('Machine Shoulder Press', ARRAY['Machine']::text[], 'Machine', 'Anterior Deltoid', ARRAY['Lateral Deltoid','Triceps']::text[], 'Shoulders', 'Push', 'press'),
  ('Smith Machine Shoulder Press', ARRAY['Smith Machine','Bench']::text[], 'Machine', 'Anterior Deltoid', ARRAY['Lateral Deltoid','Triceps']::text[], 'Shoulders', 'Push', 'press'),
  ('Barbell Push Press', ARRAY['Barbell']::text[], 'Barbell', 'Anterior Deltoid', ARRAY['Triceps','Quads','Core']::text[], 'Shoulders', 'Push', 'press'),
  ('Dumbbell Push Press', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Anterior Deltoid', ARRAY['Triceps','Quads','Core']::text[], 'Shoulders', 'Push', 'press'),
  ('Dumbbell Lateral Raise', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Lateral Deltoid', ARRAY['Anterior Deltoid','Upper Traps']::text[], 'Shoulders', 'Push', 'raise'),
  ('Cable Lateral Raise', ARRAY['Cable Machine']::text[], 'Cable', 'Lateral Deltoid', ARRAY['Anterior Deltoid','Upper Traps']::text[], 'Shoulders', 'Push', 'raise'),
  ('Machine Lateral Raise', ARRAY['Machine']::text[], 'Machine', 'Lateral Deltoid', ARRAY['Anterior Deltoid','Upper Traps']::text[], 'Shoulders', 'Push', 'raise'),
  ('Dumbbell Front Raise', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Anterior Deltoid', ARRAY['Lateral Deltoid','Upper Traps']::text[], 'Shoulders', 'Push', 'raise'),
  ('Barbell Front Raise', ARRAY['Barbell']::text[], 'Barbell', 'Anterior Deltoid', ARRAY['Lateral Deltoid','Upper Traps']::text[], 'Shoulders', 'Push', 'raise'),
  ('Cable Front Raise', ARRAY['Cable Machine']::text[], 'Cable', 'Anterior Deltoid', ARRAY['Lateral Deltoid','Upper Traps']::text[], 'Shoulders', 'Push', 'raise'),
  ('Plate Front Raise', ARRAY['Weight Plate']::text[], 'Other', 'Anterior Deltoid', ARRAY['Lateral Deltoid','Upper Traps']::text[], 'Shoulders', 'Push', 'raise'),
  ('Seated Dumbbell Lateral Raise', ARRAY['Dumbbells','Bench']::text[], 'Dumbbell', 'Lateral Deltoid', ARRAY['Anterior Deltoid','Upper Traps']::text[], 'Shoulders', 'Push', 'raise'),
  ('Egyptian Cable Lateral Raise', ARRAY['Cable Machine']::text[], 'Cable', 'Lateral Deltoid', ARRAY['Anterior Deltoid','Upper Traps']::text[], 'Shoulders', 'Push', 'raise'),
  ('Leaning Dumbbell Lateral Raise', ARRAY['Dumbbell','Squat Rack']::text[], 'Dumbbell', 'Lateral Deltoid', ARRAY['Anterior Deltoid','Upper Traps']::text[], 'Shoulders', 'Push', 'raise'),
  ('Barbell Upright Row', ARRAY['Barbell']::text[], 'Barbell', 'Lateral Deltoid, Upper Traps', ARRAY['Biceps','Brachialis']::text[], 'Shoulders', 'Pull', 'row'),
  ('Dumbbell Upright Row', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Lateral Deltoid, Upper Traps', ARRAY['Biceps','Brachialis']::text[], 'Shoulders', 'Pull', 'row'),
  ('Cable Upright Row', ARRAY['Cable Machine']::text[], 'Cable', 'Lateral Deltoid, Upper Traps', ARRAY['Biceps','Brachialis']::text[], 'Shoulders', 'Pull', 'row'),
  ('Barbell Z-Press', ARRAY['Barbell']::text[], 'Barbell', 'Anterior Deltoid', ARRAY['Triceps','Core']::text[], 'Shoulders', 'Push', 'press'),
  ('Dumbbell Z-Press', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Anterior Deltoid', ARRAY['Triceps','Core']::text[], 'Shoulders', 'Push', 'press'),
  ('Single-Arm Landmine Press', ARRAY['Barbell','Landmine']::text[], 'Barbell', 'Anterior Deltoid', ARRAY['Upper Chest','Triceps']::text[], 'Shoulders', 'Push', 'press'),
  ('Kettlebell Overhead Press', ARRAY['Kettlebells']::text[], 'Kettlebell', 'Anterior Deltoid', ARRAY['Lateral Deltoid','Triceps']::text[], 'Shoulders', 'Push', 'press'),
  ('Smith Close-Grip Press', ARRAY['Smith Machine','Bench']::text[], 'Machine', 'Triceps', ARRAY['Pectoralis Major','Anterior Deltoid']::text[], 'Triceps', 'Push', 'press'),
  ('EZ-Bar Skullcrusher', ARRAY['EZ-Bar','Bench']::text[], 'Barbell', 'Triceps (Long Head)', ARRAY['Forearms']::text[], 'Triceps', 'Push', 'extension'),
  ('Dumbbell Skullcrusher', ARRAY['Dumbbells','Bench']::text[], 'Dumbbell', 'Triceps (Long Head)', ARRAY['Forearms']::text[], 'Triceps', 'Push', 'extension'),
  ('Cable Lying Tricep Extension', ARRAY['Cable Machine','Bench']::text[], 'Cable', 'Triceps', ARRAY['Forearms']::text[], 'Triceps', 'Push', 'extension'),
  ('Seated Dumbbell Overhead Ext.', ARRAY['Dumbbell','Bench']::text[], 'Dumbbell', 'Triceps (Long Head)', ARRAY['Shoulders']::text[], 'Triceps', 'Push', 'push'),
  ('Standing Single-Arm DB Ext.', ARRAY['Dumbbell']::text[], 'Dumbbell', 'Triceps (Long Head)', ARRAY['Shoulders']::text[], 'Triceps', 'Push', 'push'),
  ('Cable Rope Overhead Ext.', ARRAY['Cable Machine']::text[], 'Cable', 'Triceps (Long Head)', ARRAY['Forearms']::text[], 'Triceps', 'Push', 'push'),
  ('EZ-Bar Overhead Ext.', ARRAY['EZ-Bar','Bench']::text[], 'Barbell', 'Triceps (Long Head)', ARRAY['Forearms']::text[], 'Triceps', 'Push', 'push'),
  ('Cable Rope Tricep Pushdown', ARRAY['Cable Machine']::text[], 'Cable', 'Triceps (Lateral Head)', ARRAY['Forearms']::text[], 'Triceps', 'Push', 'extension'),
  ('Cable Straight Bar Pushdown', ARRAY['Cable Machine']::text[], 'Cable', 'Triceps (Lateral/Medial)', ARRAY['Forearms']::text[], 'Triceps', 'Push', 'extension'),
  ('Cable V-Bar Pushdown', ARRAY['Cable Machine']::text[], 'Cable', 'Triceps (Lateral Head)', ARRAY['Forearms']::text[], 'Triceps', 'Push', 'extension'),
  ('Cable Reverse-Grip Pushdown', ARRAY['Cable Machine']::text[], 'Cable', 'Triceps (Medial Head)', ARRAY['Forearms']::text[], 'Triceps', 'Push', 'extension'),
  ('Single-Arm Cable Pushdown', ARRAY['Cable Machine']::text[], 'Cable', 'Triceps', ARRAY['Forearms']::text[], 'Triceps', 'Push', 'extension'),
  ('Dumbbell Tricep Kickback', ARRAY['Dumbbells','Bench']::text[], 'Dumbbell', 'Triceps', ARRAY['Rear Deltoid']::text[], 'Triceps', 'Push', 'extension'),
  ('Cable Tricep Kickback', ARRAY['Cable Machine']::text[], 'Cable', 'Triceps', ARRAY['Rear Deltoid']::text[], 'Triceps', 'Push', 'extension'),
  ('Tate Press', ARRAY['Dumbbells','Bench']::text[], 'Dumbbell', 'Triceps', ARRAY['Pectoralis Major']::text[], 'Triceps', 'Push', 'press'),
  ('JM Press', ARRAY['Barbell','Bench']::text[], 'Barbell', 'Triceps', ARRAY['Pectoralis Major']::text[], 'Triceps', 'Push', 'press'),
  ('Bodyweight Bench Dip', ARRAY['Bench']::text[], 'Other', 'Triceps', ARRAY['Lower Chest','Anterior Deltoid']::text[], 'Triceps', 'Push', 'press'),
  ('Machine Tricep Extension', ARRAY['Machine']::text[], 'Machine', 'Triceps', ARRAY['Forearms']::text[], 'Triceps', 'Push', 'extension'),
  ('Bodyweight Pull-Up', ARRAY['Pull-Up Bar']::text[], 'Bodyweight', 'Latissimus Dorsi', ARRAY['Biceps','Rhomboids','Lower Traps']::text[], 'Back', 'Pull', 'vertical pull'),
  ('Weighted Pull-Up', ARRAY['Bar','Belt/Vest']::text[], 'Other', 'Latissimus Dorsi', ARRAY['Biceps','Rhomboids','Lower Traps']::text[], 'Back', 'Pull', 'vertical pull'),
  ('Machine Assisted Pull-Up', ARRAY['Assisted Machine']::text[], 'Other', 'Latissimus Dorsi', ARRAY['Biceps','Rhomboids','Lower Traps']::text[], 'Back', 'Pull', 'vertical pull'),
  ('Bodyweight Chin-Up', ARRAY['Pull-Up Bar']::text[], 'Bodyweight', 'Latissimus Dorsi, Biceps', ARRAY['Rhomboids','Lower Traps']::text[], 'Back', 'Pull', 'vertical pull'),
  ('Weighted Chin-Up', ARRAY['Bar','Belt/Vest']::text[], 'Other', 'Latissimus Dorsi, Biceps', ARRAY['Rhomboids','Lower Traps']::text[], 'Back', 'Pull', 'vertical pull'),
  ('Wide-Grip Lat Pulldown', ARRAY['Cable Machine']::text[], 'Cable', 'Latissimus Dorsi', ARRAY['Biceps','Rhomboids']::text[], 'Back', 'Pull', 'vertical pull'),
  ('Close-Grip Neutral Pulldown', ARRAY['Cable Machine']::text[], 'Cable', 'Latissimus Dorsi', ARRAY['Biceps','Rhomboids']::text[], 'Back', 'Pull', 'vertical pull'),
  ('Underhand Lat Pulldown', ARRAY['Cable Machine']::text[], 'Cable', 'Latissimus Dorsi, Biceps', ARRAY['Rhomboids']::text[], 'Back', 'Pull', 'vertical pull'),
  ('Single-Arm Cable Pulldown', ARRAY['Cable Machine']::text[], 'Cable', 'Latissimus Dorsi', ARRAY['Biceps','Rhomboids']::text[], 'Back', 'Pull', 'vertical pull'),
  ('Machine Lat Pulldown', ARRAY['Machine']::text[], 'Machine', 'Latissimus Dorsi', ARRAY['Biceps','Rhomboids']::text[], 'Back', 'Pull', 'vertical pull'),
  ('Barbell Bent-Over Row', ARRAY['Barbell']::text[], 'Barbell', 'Latissimus Dorsi, Rhomboids', ARRAY['Biceps','Erector Spinae']::text[], 'Back', 'Pull', 'row'),
  ('Barbell Pendlay Row', ARRAY['Barbell']::text[], 'Barbell', 'Latissimus Dorsi, Rhomboids', ARRAY['Biceps','Erector Spinae']::text[], 'Back', 'Pull', 'row'),
  ('Barbell Yates Row', ARRAY['Barbell']::text[], 'Barbell', 'Latissimus Dorsi, Traps', ARRAY['Biceps','Erector Spinae']::text[], 'Back', 'Pull', 'row'),
  ('Barbell Underhand Row', ARRAY['Barbell']::text[], 'Barbell', 'Latissimus Dorsi, Biceps', ARRAY['Rhomboids','Erector Spinae']::text[], 'Back', 'Pull', 'row'),
  ('Single-Arm Dumbbell Row', ARRAY['Dumbbell','Bench']::text[], 'Dumbbell', 'Latissimus Dorsi', ARRAY['Biceps','Rhomboids','Traps']::text[], 'Back', 'Pull', 'row'),
  ('Dumbbell Chest-Supported Row', ARRAY['Dumbbells','Incline Bench']::text[], 'Dumbbell', 'Rhomboids, Mid Traps', ARRAY['Latissimus Dorsi','Biceps']::text[], 'Back', 'Pull', 'row'),
  ('Dumbbell Seal Row', ARRAY['Dumbbells','High Bench']::text[], 'Dumbbell', 'Rhomboids, Mid Traps', ARRAY['Latissimus Dorsi','Biceps']::text[], 'Back', 'Pull', 'row'),
  ('Renegade Row', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Latissimus Dorsi, Core', ARRAY['Biceps','Rhomboids']::text[], 'Back', 'Pull', 'row'),
  ('Seated Cable Row (Narrow)', ARRAY['Cable Machine']::text[], 'Cable', 'Latissimus Dorsi, Rhomboids', ARRAY['Biceps','Mid Traps']::text[], 'Back', 'Pull', 'row'),
  ('Seated Cable Row (Wide)', ARRAY['Cable Machine']::text[], 'Cable', 'Rhomboids, Mid Traps', ARRAY['Latissimus Dorsi','Biceps']::text[], 'Back', 'Pull', 'row'),
  ('Single-Arm Cable Row', ARRAY['Cable Machine']::text[], 'Cable', 'Latissimus Dorsi', ARRAY['Biceps','Rhomboids']::text[], 'Back', 'Pull', 'row'),
  ('T-Bar Row (Chest-Supported)', ARRAY['T-Bar Machine']::text[], 'Other', 'Rhomboids, Mid Traps', ARRAY['Latissimus Dorsi','Biceps']::text[], 'Back', 'Pull', 'row'),
  ('T-Bar Row (Landmine)', ARRAY['Barbell','Landmine']::text[], 'Barbell', 'Latissimus Dorsi, Rhomboids', ARRAY['Biceps','Erector Spinae']::text[], 'Back', 'Pull', 'row'),
  ('Machine High Row', ARRAY['Machine']::text[], 'Machine', 'Latissimus Dorsi, Rhomboids', ARRAY['Biceps','Traps']::text[], 'Back', 'Pull', 'row'),
  ('Machine Mid Row', ARRAY['Machine']::text[], 'Machine', 'Rhomboids, Mid Traps', ARRAY['Latissimus Dorsi','Biceps']::text[], 'Back', 'Pull', 'row'),
  ('Machine Low Row', ARRAY['Machine']::text[], 'Machine', 'Latissimus Dorsi', ARRAY['Biceps','Rhomboids']::text[], 'Back', 'Pull', 'row'),
  ('Cable Straight-Arm Pulldown', ARRAY['Cable Machine']::text[], 'Cable', 'Latissimus Dorsi', ARRAY['Teres Major','Triceps (Long Head)']::text[], 'Back', 'Pull', 'vertical pull'),
  ('Rack Pull', ARRAY['Barbell','Power Rack']::text[], 'Barbell', 'Erector Spinae, Traps', ARRAY['Latissimus Dorsi','Glutes']::text[], 'Back', 'Pull', 'hinge'),
  ('Bodyweight Back Extension', ARRAY['Roman Chair']::text[], 'Other', 'Erector Spinae', ARRAY['Glutes','Hamstrings']::text[], 'Back', 'Pull', 'extension'),
  ('Weighted Back Extension', ARRAY['Roman Chair','Plate']::text[], 'Other', 'Erector Spinae', ARRAY['Glutes','Hamstrings']::text[], 'Back', 'Pull', 'extension'),
  ('Machine Back Extension', ARRAY['Machine']::text[], 'Machine', 'Erector Spinae', ARRAY['Glutes','Hamstrings']::text[], 'Back', 'Pull', 'extension'),
  ('Barbell Good Morning', ARRAY['Barbell']::text[], 'Barbell', 'Erector Spinae, Hamstrings', ARRAY['Glutes']::text[], 'Back', 'Pull', 'hinge'),
  ('Seated Barbell Good Morning', ARRAY['Barbell','Bench']::text[], 'Barbell', 'Erector Spinae', ARRAY['Lower Back','Glutes']::text[], 'Back', 'Pull', 'hinge'),
  ('Machine Reverse Pec Deck', ARRAY['Machine']::text[], 'Machine', 'Posterior Deltoid', ARRAY['Rhomboids','Mid Traps']::text[], 'Rear Delts', 'Pull', 'pull'),
  ('Cable Face Pull', ARRAY['Cable Machine','Rope']::text[], 'Cable', 'Posterior Deltoid, Mid Traps', ARRAY['Rhomboids','Rotator Cuff']::text[], 'Rear Delts', 'Pull', 'row'),
  ('Bent-Over Dumbbell Reverse Fly', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Posterior Deltoid', ARRAY['Rhomboids','Mid Traps']::text[], 'Rear Delts', 'Pull', 'fly'),
  ('Standing Cable Reverse Fly', ARRAY['Cable Machine']::text[], 'Cable', 'Posterior Deltoid', ARRAY['Rhomboids','Mid Traps']::text[], 'Rear Delts', 'Pull', 'fly'),
  ('Wide-Grip Barbell Rear Delt Row', ARRAY['Barbell']::text[], 'Barbell', 'Posterior Deltoid, Rhomboids', ARRAY['Mid Traps','Biceps']::text[], 'Rear Delts', 'Pull', 'row'),
  ('Wide-Grip Dumbbell Rear Delt Row', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Posterior Deltoid, Rhomboids', ARRAY['Mid Traps','Biceps']::text[], 'Rear Delts', 'Pull', 'row'),
  ('Barbell Shrug', ARRAY['Barbell']::text[], 'Barbell', 'Upper Trapezius', ARRAY['Forearms','Levator Scapulae']::text[], 'Traps', 'Pull', 'shrug'),
  ('Dumbbell Shrug', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Upper Trapezius', ARRAY['Forearms','Levator Scapulae']::text[], 'Traps', 'Pull', 'shrug'),
  ('Trap Bar Shrug', ARRAY['Trap Bar']::text[], 'Barbell', 'Upper Trapezius', ARRAY['Forearms','Levator Scapulae']::text[], 'Traps', 'Pull', 'shrug'),
  ('Smith Machine Shrug', ARRAY['Smith Machine']::text[], 'Machine', 'Upper Trapezius', ARRAY['Forearms','Levator Scapulae']::text[], 'Traps', 'Pull', 'shrug'),
  ('Cable Shrug', ARRAY['Cable Machine']::text[], 'Cable', 'Upper Trapezius', ARRAY['Forearms','Levator Scapulae']::text[], 'Traps', 'Pull', 'shrug'),
  ('Machine Shrug', ARRAY['Machine']::text[], 'Machine', 'Upper Trapezius', ARRAY['Forearms','Levator Scapulae']::text[], 'Traps', 'Pull', 'shrug'),
  ('Barbell Bicep Curl', ARRAY['Barbell']::text[], 'Barbell', 'Biceps Brachii', ARRAY['Brachialis','Forearms']::text[], 'Biceps', 'Pull', 'curl'),
  ('EZ-Bar Bicep Curl', ARRAY['EZ-Bar']::text[], 'Barbell', 'Biceps Brachii', ARRAY['Brachialis','Forearms']::text[], 'Biceps', 'Pull', 'curl'),
  ('Alternating Dumbbell Curl', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Biceps Brachii', ARRAY['Brachialis','Forearms']::text[], 'Biceps', 'Pull', 'curl'),
  ('Supinating Dumbbell Curl', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Biceps Brachii', ARRAY['Brachialis','Forearms']::text[], 'Biceps', 'Pull', 'curl'),
  ('Seated Incline Dumbbell Curl', ARRAY['Dumbbells','Incline Bench']::text[], 'Dumbbell', 'Biceps (Long Head)', ARRAY['Brachialis','Forearms']::text[], 'Biceps', 'Pull', 'curl'),
  ('Dumbbell Concentration Curl', ARRAY['Dumbbell','Bench']::text[], 'Dumbbell', 'Biceps Brachii', ARRAY['Brachialis','Forearms']::text[], 'Biceps', 'Pull', 'curl'),
  ('Dumbbell Hammer Curl', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Brachioradialis, Brachialis', ARRAY['Biceps Brachii']::text[], 'Biceps', 'Pull', 'curl'),
  ('Cable Rope Hammer Curl', ARRAY['Cable Machine','Rope']::text[], 'Cable', 'Brachioradialis, Brachialis', ARRAY['Biceps Brachii']::text[], 'Biceps', 'Pull', 'curl'),
  ('Cable Straight Bar Curl', ARRAY['Cable Machine']::text[], 'Cable', 'Biceps Brachii', ARRAY['Brachialis','Forearms']::text[], 'Biceps', 'Pull', 'curl'),
  ('High Cable Double Bicep Curl', ARRAY['Cable Machine']::text[], 'Cable', 'Biceps Brachii', ARRAY['Brachialis','Forearms']::text[], 'Biceps', 'Pull', 'curl'),
  ('Single-Arm Cable Curl', ARRAY['Cable Machine']::text[], 'Cable', 'Biceps Brachii', ARRAY['Brachialis','Forearms']::text[], 'Biceps', 'Pull', 'curl'),
  ('EZ-Bar Preacher Curl', ARRAY['EZ-Bar','Preacher Bench']::text[], 'Barbell', 'Biceps (Short Head)', ARRAY['Brachialis','Forearms']::text[], 'Biceps', 'Pull', 'curl'),
  ('Dumbbell Preacher Curl', ARRAY['Dumbbell','Preacher Bench']::text[], 'Dumbbell', 'Biceps (Short Head)', ARRAY['Brachialis','Forearms']::text[], 'Biceps', 'Pull', 'curl'),
  ('Machine Preacher Curl', ARRAY['Machine']::text[], 'Machine', 'Biceps (Short Head)', ARRAY['Brachialis','Forearms']::text[], 'Biceps', 'Pull', 'curl'),
  ('Dumbbell Spider Curl', ARRAY['Dumbbells','Incline Bench']::text[], 'Dumbbell', 'Biceps (Short Head)', ARRAY['Brachialis','Forearms']::text[], 'Biceps', 'Pull', 'curl'),
  ('EZ-Bar Spider Curl', ARRAY['EZ-Bar','Incline Bench']::text[], 'Barbell', 'Biceps (Short Head)', ARRAY['Brachialis','Forearms']::text[], 'Biceps', 'Pull', 'curl'),
  ('Barbell Drag Curl', ARRAY['Barbell']::text[], 'Barbell', 'Biceps Brachii', ARRAY['Brachialis','Forearms']::text[], 'Biceps', 'Pull', 'curl'),
  ('Zottman Curl', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Biceps, Brachioradialis', ARRAY['Brachialis','Forearms']::text[], 'Biceps', 'Pull', 'curl'),
  ('Reverse Barbell Curl', ARRAY['Barbell']::text[], 'Barbell', 'Brachioradialis', ARRAY['Brachialis','Biceps Brachii']::text[], 'Forearms', 'Pull', 'curl'),
  ('Reverse EZ-Bar Curl', ARRAY['EZ-Bar']::text[], 'Barbell', 'Brachioradialis', ARRAY['Brachialis','Biceps Brachii']::text[], 'Forearms', 'Pull', 'curl'),
  ('Barbell Wrist Curl', ARRAY['Barbell','Bench']::text[], 'Barbell', 'Forearm Flexors', ARRAY['None']::text[], 'Forearms', 'Pull', 'curl'),
  ('Dumbbell Wrist Curl', ARRAY['Dumbbells','Bench']::text[], 'Dumbbell', 'Forearm Flexors', ARRAY['None']::text[], 'Forearms', 'Pull', 'curl'),
  ('Barbell Reverse Wrist Curl', ARRAY['Barbell','Bench']::text[], 'Barbell', 'Forearm Extensors', ARRAY['None']::text[], 'Forearms', 'Pull', 'curl'),
  ('Plate Pinch Hold', ARRAY['Weight Plates']::text[], 'Other', 'Grip / Forearms', ARRAY['None']::text[], 'Forearms', 'Pull', 'isometric core'),
  ('Farmer''s Walk', ARRAY['Dumbbells / Kettlebells']::text[], 'Other', 'Grip / Forearms', ARRAY['Traps','Core','Legs']::text[], 'Forearms', 'Compound', 'carry'),
  ('Barbell High-Bar Back Squat', ARRAY['Barbell','Rack']::text[], 'Barbell', 'Quadriceps', ARRAY['Glutes','Adductors','Core']::text[], 'Quads', 'Legs', 'squat'),
  ('Barbell Low-Bar Back Squat', ARRAY['Barbell','Rack']::text[], 'Barbell', 'Quadriceps, Glutes', ARRAY['Hamstrings','Adductors','Core']::text[], 'Quads', 'Legs', 'squat'),
  ('Barbell Front Squat', ARRAY['Barbell','Rack']::text[], 'Barbell', 'Quadriceps', ARRAY['Glutes','Core','Upper Back']::text[], 'Quads', 'Legs', 'squat'),
  ('Barbell Zercher Squat', ARRAY['Barbell','Rack']::text[], 'Barbell', 'Quadriceps', ARRAY['Glutes','Core','Upper Back']::text[], 'Quads', 'Legs', 'squat'),
  ('Barbell Box Squat', ARRAY['Barbell','Box']::text[], 'Barbell', 'Quadriceps, Glutes', ARRAY['Hamstrings','Adductors','Core']::text[], 'Quads', 'Legs', 'squat'),
  ('Barbell Pause Squat', ARRAY['Barbell','Rack']::text[], 'Barbell', 'Quadriceps', ARRAY['Glutes','Adductors','Core']::text[], 'Quads', 'Legs', 'squat'),
  ('Barbell Overhead Squat', ARRAY['Barbell','Rack']::text[], 'Barbell', 'Quadriceps', ARRAY['Glutes','Shoulders','Core']::text[], 'Quads', 'Legs', 'squat'),
  ('Smith Machine Squat', ARRAY['Smith Machine']::text[], 'Machine', 'Quadriceps', ARRAY['Glutes','Adductors']::text[], 'Quads', 'Legs', 'squat'),
  ('Dumbbell Goblet Squat', ARRAY['Dumbbell']::text[], 'Dumbbell', 'Quadriceps', ARRAY['Glutes','Core']::text[], 'Quads', 'Legs', 'squat'),
  ('Kettlebell Goblet Squat', ARRAY['Kettlebell']::text[], 'Kettlebell', 'Quadriceps', ARRAY['Glutes','Core']::text[], 'Quads', 'Legs', 'squat'),
  ('Dumbbell Bulgarian Split Squat', ARRAY['Dumbbells','Bench']::text[], 'Dumbbell', 'Quadriceps, Glutes', ARRAY['Hamstrings','Adductors']::text[], 'Quads', 'Legs', 'squat'),
  ('Barbell Bulgarian Split Squat', ARRAY['Barbell','Bench']::text[], 'Barbell', 'Quadriceps, Glutes', ARRAY['Hamstrings','Adductors']::text[], 'Quads', 'Legs', 'squat'),
  ('Dumbbell Standard Split Squat', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Quadriceps, Glutes', ARRAY['Hamstrings','Adductors']::text[], 'Quads', 'Legs', 'squat'),
  ('DB Front-Foot Elevated Split', ARRAY['Dumbbells','Plate/Block']::text[], 'Dumbbell', 'Quadriceps', ARRAY['Glutes','Hamstrings']::text[], 'Quads', 'Legs', 'squat'),
  ('Dumbbell Walking Lunge', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Quadriceps, Glutes', ARRAY['Hamstrings','Adductors']::text[], 'Quads', 'Legs', 'lunge'),
  ('Barbell Walking Lunge', ARRAY['Barbell']::text[], 'Barbell', 'Quadriceps, Glutes', ARRAY['Hamstrings','Adductors']::text[], 'Quads', 'Legs', 'lunge'),
  ('Dumbbell Reverse Lunge', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Quadriceps, Glutes', ARRAY['Hamstrings','Adductors']::text[], 'Quads', 'Legs', 'lunge'),
  ('Barbell Reverse Lunge', ARRAY['Barbell']::text[], 'Barbell', 'Quadriceps, Glutes', ARRAY['Hamstrings','Adductors']::text[], 'Quads', 'Legs', 'lunge'),
  ('Dumbbell Forward Lunge', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Quadriceps', ARRAY['Glutes','Hamstrings']::text[], 'Quads', 'Legs', 'lunge'),
  ('Machine Leg Press', ARRAY['Leg Press Machine']::text[], 'Machine', 'Quadriceps', ARRAY['Glutes','Hamstrings']::text[], 'Quads', 'Legs', 'press'),
  ('Single-Leg Leg Press', ARRAY['Leg Press Machine']::text[], 'Machine', 'Quadriceps', ARRAY['Glutes','Hamstrings']::text[], 'Quads', 'Legs', 'press'),
  ('Machine Hack Squat', ARRAY['Hack Squat Machine']::text[], 'Other', 'Quadriceps', ARRAY['Glutes','Adductors']::text[], 'Quads', 'Legs', 'squat'),
  ('Barbell Hack Squat', ARRAY['Barbell']::text[], 'Barbell', 'Quadriceps', ARRAY['Glutes','Adductors','Forearms']::text[], 'Quads', 'Legs', 'squat'),
  ('Machine Pendulum Squat', ARRAY['Pendulum Machine']::text[], 'Other', 'Quadriceps', ARRAY['Glutes','Adductors']::text[], 'Quads', 'Legs', 'squat'),
  ('Machine V-Squat', ARRAY['V-Squat Machine']::text[], 'Other', 'Quadriceps', ARRAY['Glutes','Adductors']::text[], 'Quads', 'Legs', 'squat'),
  ('Machine Leg Extension', ARRAY['Leg Extension Machine']::text[], 'Other', 'Quadriceps', ARRAY['None']::text[], 'Quads', 'Legs', 'extension'),
  ('Single-Leg Leg Extension', ARRAY['Leg Extension Machine']::text[], 'Other', 'Quadriceps', ARRAY['None']::text[], 'Quads', 'Legs', 'extension'),
  ('Bodyweight Sissy Squat', ARRAY['None']::text[], 'Bodyweight', 'Quadriceps', ARRAY['Core']::text[], 'Quads', 'Legs', 'squat'),
  ('Weighted Sissy Squat', ARRAY['Plate / Vest']::text[], 'Other', 'Quadriceps', ARRAY['Core']::text[], 'Quads', 'Legs', 'squat'),
  ('Dumbbell Step-Up', ARRAY['Dumbbells','Box']::text[], 'Dumbbell', 'Quadriceps, Glutes', ARRAY['Hamstrings','Core']::text[], 'Quads', 'Legs', 'lunge'),
  ('Barbell Romanian Deadlift', ARRAY['Barbell']::text[], 'Barbell', 'Hamstrings, Glutes', ARRAY['Erector Spinae','Forearms']::text[], 'Hamstrings', 'Legs', 'hinge'),
  ('Dumbbell Romanian Deadlift', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Hamstrings, Glutes', ARRAY['Erector Spinae','Forearms']::text[], 'Hamstrings', 'Legs', 'hinge'),
  ('Single-Leg Dumbbell RDL', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Hamstrings, Glutes', ARRAY['Erector Spinae','Core']::text[], 'Hamstrings', 'Legs', 'hinge'),
  ('Trap Bar Romanian Deadlift', ARRAY['Trap Bar']::text[], 'Barbell', 'Hamstrings, Glutes', ARRAY['Erector Spinae','Forearms']::text[], 'Hamstrings', 'Legs', 'hinge'),
  ('Cable Pull-Through', ARRAY['Cable Machine']::text[], 'Cable', 'Glutes, Hamstrings', ARRAY['Erector Spinae']::text[], 'Glutes', 'Legs', 'hinge'),
  ('Barbell Stiff-Leg Deadlift', ARRAY['Barbell']::text[], 'Barbell', 'Hamstrings', ARRAY['Glutes','Erector Spinae']::text[], 'Hamstrings', 'Legs', 'hinge'),
  ('Dumbbell Stiff-Leg Deadlift', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Hamstrings', ARRAY['Glutes','Erector Spinae']::text[], 'Hamstrings', 'Legs', 'hinge'),
  ('Machine Lying Leg Curl', ARRAY['Machine']::text[], 'Machine', 'Hamstrings', ARRAY['Calves']::text[], 'Hamstrings', 'Legs', 'curl'),
  ('Machine Seated Leg Curl', ARRAY['Machine']::text[], 'Machine', 'Hamstrings', ARRAY['Calves']::text[], 'Hamstrings', 'Legs', 'curl'),
  ('Standing Single-Leg Curl', ARRAY['Machine']::text[], 'Machine', 'Hamstrings', ARRAY['Calves']::text[], 'Hamstrings', 'Legs', 'curl'),
  ('Nordic Hamstring Curl', ARRAY['Pad / Partner']::text[], 'Other', 'Hamstrings', ARRAY['Glutes','Calves']::text[], 'Hamstrings', 'Legs', 'curl'),
  ('Glute-Ham Raise (GHR)', ARRAY['GHR Machine']::text[], 'Other', 'Hamstrings, Glutes', ARRAY['Erector Spinae','Calves']::text[], 'Hamstrings', 'Legs', 'raise'),
  ('Dumbbell Leg Curl', ARRAY['Dumbbell','Bench']::text[], 'Dumbbell', 'Hamstrings', ARRAY['Calves']::text[], 'Hamstrings', 'Legs', 'curl'),
  ('Swiss Ball Hamstring Curl', ARRAY['Swiss Ball']::text[], 'Other', 'Hamstrings', ARRAY['Glutes','Core']::text[], 'Hamstrings', 'Legs', 'curl'),
  ('Kettlebell Swing', ARRAY['Kettlebell']::text[], 'Kettlebell', 'Glutes, Hamstrings', ARRAY['Core','Lower Back']::text[], 'Glutes', 'Compound', 'hinge'),
  ('Barbell Hip Thrust', ARRAY['Barbell','Bench']::text[], 'Barbell', 'Glutes', ARRAY['Hamstrings','Quads','Core']::text[], 'Glutes', 'Legs', 'hinge'),
  ('Machine Hip Thrust', ARRAY['Machine']::text[], 'Machine', 'Glutes', ARRAY['Hamstrings','Quads','Core']::text[], 'Glutes', 'Legs', 'hinge'),
  ('Single-Leg Dumbbell Thrust', ARRAY['Dumbbell','Bench']::text[], 'Dumbbell', 'Glutes', ARRAY['Hamstrings','Quads','Core']::text[], 'Glutes', 'Legs', 'legs'),
  ('Bodyweight Glute Bridge', ARRAY['Floor']::text[], 'Bodyweight', 'Glutes', ARRAY['Hamstrings','Core']::text[], 'Glutes', 'Legs', 'hinge'),
  ('Barbell Glute Bridge', ARRAY['Barbell','Floor']::text[], 'Barbell', 'Glutes', ARRAY['Hamstrings','Core']::text[], 'Glutes', 'Legs', 'hinge'),
  ('Cable Glute Kickback', ARRAY['Cable Machine','Ankle Cuff']::text[], 'Cable', 'Glutes', ARRAY['Hamstrings']::text[], 'Glutes', 'Legs', 'extension'),
  ('Machine Glute Kickback', ARRAY['Machine']::text[], 'Machine', 'Glutes', ARRAY['Hamstrings']::text[], 'Glutes', 'Legs', 'extension'),
  ('Banded Glute Kickback', ARRAY['Resistance Band']::text[], 'Other', 'Glutes', ARRAY['Hamstrings']::text[], 'Glutes', 'Legs', 'extension'),
  ('Machine Seated Hip Abduction', ARRAY['Machine']::text[], 'Machine', 'Gluteus Medius / Minimus', ARRAY['Tensor Fasciae Latae (TFL)']::text[], 'Glutes', 'Legs', 'abduction'),
  ('Cable Standing Hip Abduction', ARRAY['Cable Machine','Ankle Cuff']::text[], 'Cable', 'Gluteus Medius / Minimus', ARRAY['Core']::text[], 'Glutes', 'Legs', 'abduction'),
  ('Banded Clamshell', ARRAY['Resistance Band']::text[], 'Other', 'Gluteus Medius / Minimus', ARRAY['TFL']::text[], 'Glutes', 'Legs', 'legs'),
  ('Dumbbell Curtsy Lunge', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Glutes, Quads', ARRAY['Hamstrings','Adductors']::text[], 'Glutes', 'Legs', 'lunge'),
  ('Deficit Reverse Lunge', ARRAY['Dumbbells','Plate']::text[], 'Dumbbell', 'Glutes, Quads', ARRAY['Hamstrings','Adductors']::text[], 'Glutes', 'Legs', 'lunge'),
  ('Frog Pumps', ARRAY['Floor']::text[], 'Bodyweight', 'Glutes', ARRAY['Core']::text[], 'Glutes', 'Legs', 'legs'),
  ('Machine Standing Calf Raise', ARRAY['Machine']::text[], 'Machine', 'Gastrocnemius', ARRAY['Soleus']::text[], 'Calves', 'Legs', 'raise'),
  ('Smith Standing Calf Raise', ARRAY['Smith Machine','Block']::text[], 'Machine', 'Gastrocnemius', ARRAY['Soleus']::text[], 'Calves', 'Legs', 'raise'),
  ('Dumbbell Standing Calf Raise', ARRAY['Dumbbells','Block']::text[], 'Dumbbell', 'Gastrocnemius', ARRAY['Soleus']::text[], 'Calves', 'Legs', 'raise'),
  ('Single-Leg Bodyweight Raise', ARRAY['Block / Step']::text[], 'Other', 'Gastrocnemius', ARRAY['Soleus']::text[], 'Calves', 'Legs', 'raise'),
  ('Machine Seated Calf Raise', ARRAY['Machine']::text[], 'Machine', 'Soleus', ARRAY['Gastrocnemius']::text[], 'Calves', 'Legs', 'raise'),
  ('Dumbbell Seated Calf Raise', ARRAY['Dumbbells','Bench','Block']::text[], 'Dumbbell', 'Soleus', ARRAY['Gastrocnemius']::text[], 'Calves', 'Legs', 'raise'),
  ('Leg Press Calf Raise', ARRAY['Leg Press Machine']::text[], 'Machine', 'Gastrocnemius', ARRAY['Soleus']::text[], 'Calves', 'Legs', 'press'),
  ('Machine Donkey Calf Raise', ARRAY['Machine']::text[], 'Machine', 'Gastrocnemius', ARRAY['Soleus']::text[], 'Calves', 'Legs', 'raise'),
  ('Tibialis Raise', ARRAY['Wall / Tib Bar']::text[], 'Other', 'Tibialis Anterior', ARRAY['None']::text[], 'Calves', 'Legs', 'raise'),
  ('Bodyweight Crunch', ARRAY['Floor']::text[], 'Bodyweight', 'Rectus Abdominis', ARRAY['Obliques']::text[], 'Core', 'Core', 'flexion core'),
  ('Decline Bench Crunch', ARRAY['Decline Bench']::text[], 'Other', 'Rectus Abdominis', ARRAY['Obliques']::text[], 'Core', 'Core', 'flexion core'),
  ('Cable Crunch', ARRAY['Cable Machine','Rope']::text[], 'Cable', 'Rectus Abdominis', ARRAY['Obliques','Serratus Anterior']::text[], 'Core', 'Core', 'flexion core'),
  ('Machine Crunch', ARRAY['Machine']::text[], 'Machine', 'Rectus Abdominis', ARRAY['Obliques']::text[], 'Core', 'Core', 'flexion core'),
  ('Bodyweight Sit-Up', ARRAY['Floor']::text[], 'Bodyweight', 'Rectus Abdominis', ARRAY['Hip Flexors','Obliques']::text[], 'Core', 'Core', 'flexion core'),
  ('Decline Weighted Sit-Up', ARRAY['Decline Bench','Plate']::text[], 'Other', 'Rectus Abdominis', ARRAY['Hip Flexors','Obliques']::text[], 'Core', 'Core', 'flexion core'),
  ('Hanging Straight Leg Raise', ARRAY['Pull-Up Bar']::text[], 'Bodyweight', 'Rectus Abdominis', ARRAY['Hip Flexors','Obliques']::text[], 'Core', 'Core', 'raise'),
  ('Hanging Knee Raise', ARRAY['Pull-Up Bar']::text[], 'Bodyweight', 'Rectus Abdominis', ARRAY['Hip Flexors','Obliques']::text[], 'Core', 'Core', 'raise'),
  ('Captain''s Chair Leg Raise', ARRAY['Captain''s Chair']::text[], 'Other', 'Rectus Abdominis', ARRAY['Hip Flexors','Obliques']::text[], 'Core', 'Core', 'raise'),
  ('Lying Leg Raise', ARRAY['Floor']::text[], 'Bodyweight', 'Rectus Abdominis', ARRAY['Hip Flexors']::text[], 'Core', 'Core', 'raise'),
  ('Bodyweight Plank', ARRAY['Floor']::text[], 'Bodyweight', 'Transverse Abdominis', ARRAY['Rectus Abdominis','Shoulders']::text[], 'Core', 'Core', 'isometric core'),
  ('Weighted Plank', ARRAY['Floor','Plate']::text[], 'Bodyweight', 'Transverse Abdominis', ARRAY['Rectus Abdominis','Shoulders']::text[], 'Core', 'Core', 'isometric core'),
  ('Side Plank', ARRAY['Floor']::text[], 'Bodyweight', 'Obliques', ARRAY['Transverse Abdominis','Shoulders']::text[], 'Core', 'Core', 'isometric core'),
  ('Ab Wheel Rollout', ARRAY['Ab Wheel']::text[], 'Other', 'Rectus Abdominis', ARRAY['Transverse Abdominis','Lats']::text[], 'Core', 'Core', 'core'),
  ('Weight Plate Russian Twist', ARRAY['Weight Plate']::text[], 'Other', 'Obliques', ARRAY['Rectus Abdominis','Core']::text[], 'Core', 'Core', 'rotation core'),
  ('Medicine Ball Russian Twist', ARRAY['Medicine Ball']::text[], 'Other', 'Obliques', ARRAY['Rectus Abdominis','Core']::text[], 'Core', 'Core', 'rotation core'),
  ('Cable Woodchopper', ARRAY['Cable Machine']::text[], 'Cable', 'Obliques', ARRAY['Rectus Abdominis','Shoulders']::text[], 'Core', 'Core', 'rotation core'),
  ('Medicine Ball Woodchopper', ARRAY['Medicine Ball']::text[], 'Other', 'Obliques', ARRAY['Rectus Abdominis','Shoulders']::text[], 'Core', 'Core', 'rotation core'),
  ('Bodyweight V-Up', ARRAY['Floor']::text[], 'Bodyweight', 'Rectus Abdominis', ARRAY['Hip Flexors','Obliques']::text[], 'Core', 'Core', 'core'),
  ('Hollow Body Hold', ARRAY['Floor']::text[], 'Bodyweight', 'Transverse Abdominis', ARRAY['Rectus Abdominis','Obliques']::text[], 'Core', 'Core', 'isometric core'),
  ('Cable Pallof Press', ARRAY['Cable Machine']::text[], 'Cable', 'Obliques, Core', ARRAY['Transverse Abdominis']::text[], 'Core', 'Core', 'press'),
  ('Bodyweight Dead Bug', ARRAY['Floor']::text[], 'Bodyweight', 'Transverse Abdominis', ARRAY['Rectus Abdominis']::text[], 'Core', 'Core', 'isometric core'),
  ('Bicycle Crunch', ARRAY['Floor']::text[], 'Bodyweight', 'Obliques', ARRAY['Rectus Abdominis','Hip Flexors']::text[], 'Core', 'Core', 'flexion core'),
  ('Toes to Bar', ARRAY['Pull-Up Bar']::text[], 'Bodyweight', 'Rectus Abdominis', ARRAY['Hip Flexors','Lats']::text[], 'Core', 'Core', 'core'),
  ('Windshield Wipers', ARRAY['Floor / Pull-Up Bar']::text[], 'Other', 'Obliques', ARRAY['Rectus Abdominis','Hip Flexors']::text[], 'Core', 'Core', 'core'),
  ('Barbell Conventional Deadlift', ARRAY['Barbell']::text[], 'Barbell', 'Hamstrings, Glutes, Back', ARRAY['Quads','Traps','Forearms','Core']::text[], 'Full Body', 'Compound', 'hinge'),
  ('Barbell Sumo Deadlift', ARRAY['Barbell']::text[], 'Barbell', 'Quads, Glutes, Adductors', ARRAY['Hamstrings','Back','Traps']::text[], 'Full Body', 'Compound', 'hinge'),
  ('Trap Bar Deadlift', ARRAY['Trap Bar']::text[], 'Barbell', 'Quads, Glutes, Hamstrings', ARRAY['Back','Traps','Forearms']::text[], 'Full Body', 'Compound', 'hinge'),
  ('Barbell Deficit Deadlift', ARRAY['Barbell','Plate/Block']::text[], 'Barbell', 'Hamstrings, Glutes, Back', ARRAY['Quads','Traps','Forearms']::text[], 'Full Body', 'Compound', 'hinge'),
  ('Barbell Block Pull', ARRAY['Barbell','Blocks/Rack']::text[], 'Barbell', 'Glutes, Back, Traps', ARRAY['Hamstrings','Forearms']::text[], 'Full Body', 'Compound', 'compound'),
  ('Barbell Power Clean', ARRAY['Barbell']::text[], 'Barbell', 'Glutes, Hamstrings, Back', ARRAY['Quads','Traps','Calves']::text[], 'Full Body', 'Compound', 'compound'),
  ('Dumbbell Power Clean', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Glutes, Hamstrings, Back', ARRAY['Quads','Traps','Calves']::text[], 'Full Body', 'Compound', 'compound'),
  ('Barbell Clean and Jerk', ARRAY['Barbell']::text[], 'Barbell', 'Full Body', ARRAY['Quads','Glutes','Back','Shoulders']::text[], 'Full Body', 'Compound', 'compound'),
  ('Barbell Snatch', ARRAY['Barbell']::text[], 'Barbell', 'Full Body', ARRAY['Quads','Glutes','Back','Shoulders']::text[], 'Full Body', 'Compound', 'compound'),
  ('Dumbbell Thruster', ARRAY['Dumbbells']::text[], 'Dumbbell', 'Quads, Glutes, Shoulders', ARRAY['Triceps','Core','Upper Chest']::text[], 'Full Body', 'Compound', 'compound'),
  ('Barbell Thruster', ARRAY['Barbell']::text[], 'Barbell', 'Quads, Glutes, Shoulders', ARRAY['Triceps','Core','Upper Chest']::text[], 'Full Body', 'Compound', 'compound');
